# Generated by Django 4.2.7 on 2026-02-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chargingstation_galleryimage_offer_servicelocation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargingstation',
            old_name='address',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='chargingstation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='chargingstation',
            name='longitude',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('kaweii', 'Kaweii'), ('nevko', 'Nevko'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
