# Generated by Django 4.2.7 on 2026-02-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_address_chargingstation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagehero',
            name='page',
            field=models.CharField(choices=[('about', 'About Us'), ('services', 'Services'), ('products', 'Products'), ('contact', 'Contact Us'), ('gallery', 'Gallery')], max_length=50, unique=True),
        ),
    ]
