# Generated by Django 4.2.7 on 2026-02-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chargingstation_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagehero',
            name='page',
            field=models.CharField(choices=[('about', 'About Us'), ('services', 'Services'), ('products', 'Products'), ('contact', 'Contact Us'), ('gallery', 'Gallery'), ('test-drive', 'Test Drive')], max_length=50, unique=True),
        ),
    ]
