# Generated by Django 4.2.7 on 2026-02-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_service_contact_person_service_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelocation',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
