# Generated by Django 4.2.7 on 2026-02-18 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_servicelocation_contact_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='service',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='service',
            name='location',
        ),
        migrations.CreateModel(
            name='ServiceLocationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.service')),
            ],
            options={
                'verbose_name_plural': 'Service Location Details',
                'ordering': ['order'],
            },
        ),
    ]
