# Generated by Django 4.2.7 on 2026-02-18 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_service_contact_person_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceLocation',
        ),
    ]
