# Generated by Django 4.2.7 on 2026-02-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_chatbotfaq_chatsession_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='servicelocationdetail',
            name='image',
            field=models.ImageField(blank=True, upload_to='service_locations/'),
        ),
    ]
