# Generated by Django 4.2.7 on 2026-02-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_service_image_servicelocationdetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='', upload_to='services/'),
            preserve_default=False,
        ),
    ]
