# Generated by Django 4.2.7 on 2026-02-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('charging', 'Charging Station'), ('showroom', 'Showroom'), ('service', 'Service Center'), ('restaurent', 'Restaurent')], max_length=20),
        ),
    ]
