# Generated by Django 4.2.7 on 2026-02-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='map_embed_code',
            field=models.TextField(blank=True, help_text='Paste Google Maps embed iframe code here'),
        ),
    ]
