# Generated by Django 4.2.7 on 2026-02-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_customerreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order', '-created_at'], 'verbose_name_plural': 'Gallery Media'},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='video',
            field=models.FileField(blank=True, help_text='Upload video file (MP4, WebM, etc.)', null=True, upload_to='gallery/videos/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
