# Generated by Django 4.2.7 on 2026-02-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_galleryimage_options_galleryimage_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='charging_type',
            field=models.CharField(choices=[('fast', 'Fast Charging'), ('moderate', 'Moderate Charging'), ('slow', 'Slow Charging')], default='moderate', max_length=20),
        ),
    ]
