# Generated by Django 4.2.7 on 2026-02-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_chargingstation_charging_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_title', models.CharField(help_text='e.g., Founder & CEO', max_length=200)),
                ('message', models.TextField(help_text='Message from the owner')),
                ('photo', models.ImageField(upload_to='owner/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Owner Messages',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('team_type', models.CharField(choices=[('board', 'Board of Directors'), ('technical', 'Technical Team')], max_length=20)),
                ('description', models.TextField(help_text='Short description about the person')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='team/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Team Members',
                'ordering': ['team_type', 'order'],
            },
        ),
    ]
