# Generated by Django 4.2.7 on 2026-02-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_ownermessage_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=models.CharField(help_text='Short description (max 200 characters)', max_length=200),
        ),
    ]
