# Generated by Django 4.2.7 on 2026-02-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_teammember_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='washing_facility',
            field=models.BooleanField(default=False, help_text='Check if washing facility is available'),
        ),
    ]
