# Generated by Django 4.2.7 on 2026-02-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_chargingstation_washing_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelocationdetail',
            name='charging_type',
            field=models.CharField(choices=[('none', 'None'), ('fast', 'Fast Charging'), ('moderate', 'Moderate Charging'), ('slow', 'Slow Charging')], default='none', help_text='Select charging type if available', max_length=20),
        ),
        migrations.AddField(
            model_name='servicelocationdetail',
            name='washing_facility',
            field=models.BooleanField(default=False, help_text='Check if washing facility is available'),
        ),
    ]
