# Generated by Django 4.2.7 on 2026-02-27 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_servicelocationdetail_charging_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(help_text='Brief description for card view', max_length=300)),
                ('description', models.TextField(help_text='Full description (will be displayed in italic and justified)')),
                ('cover_image', models.ImageField(upload_to='journey/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Journey',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JourneyGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='journey/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='api.journey')),
            ],
            options={
                'verbose_name_plural': 'Journey Gallery Images',
                'ordering': ['order'],
            },
        ),
    ]
