# Generated by Django 4.2.7 on 2026-02-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_journey_journeygallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagehero',
            name='page',
            field=models.CharField(choices=[('about', 'About Us'), ('services', 'Services'), ('products', 'Products'), ('contact', 'Contact Us'), ('gallery', 'Gallery'), ('test-drive', 'Test Drive'), ('journey', 'Journey')], max_length=50, unique=True),
        ),
    ]
