# Generated by Django 4.2.7 on 2026-05-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_pagehero_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herocontent',
            options={'ordering': ['order', 'id'], 'verbose_name_plural': 'Hero Content'},
        ),
        migrations.AddField(
            model_name='herocontent',
            name='order',
            field=models.IntegerField(default=0, help_text='Lower number shows first'),
        ),
    ]
