# Generated by Django 4.2.7 on 2026-05-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_hero_order_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_category',
            field=models.CharField(blank=True, help_text="Enter custom category if 'Other' is selected", max_length=100),
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('kaweii', 'Kaweii'), ('nevko', 'Nevko'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='testdriveenquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
