# Generated by Django 4.2.7 on 2026-05-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_product_custom_category_alter_customerreview_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji', max_length=50)),
                ('target_year', models.IntegerField(blank=True, help_text='Target year for this goal', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Company Goals',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year of the milestone')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='history/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Lower number shows first')),
            ],
            options={
                'verbose_name_plural': 'Company History',
                'ordering': ['order', 'year'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Mission', max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Company Mission',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Vision', max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Company Vision',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FuturePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji', max_length=50)),
                ('timeline', models.CharField(blank=True, help_text='e.g., 2025-2027, Next 5 years', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Future Plans',
                'ordering': ['order'],
            },
        ),
    ]
