# Generated by Django 4.2.7 on 2026-05-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_companygoal_companyhistory_companymission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagehero',
            name='page',
            field=models.CharField(choices=[('about', 'About Us'), ('services', 'Services'), ('products', 'Products'), ('contact', 'Contact Us'), ('gallery', 'Gallery'), ('test-drive', 'Test Drive'), ('journey', 'Journey'), ('history', 'History')], max_length=50, unique=True),
        ),
    ]
