# Generated by Django 4.2.7 on 2026-05-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_pagehero_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='companygoal',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image', null=True, upload_to='goals/'),
        ),
        migrations.AddField(
            model_name='companygoal',
            name='media_url',
            field=models.URLField(blank=True, help_text='Or provide a Google Drive/external image URL'),
        ),
        migrations.AlterField(
            model_name='companygoal',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon name or emoji (used as fallback if no image)', max_length=50),
        ),
    ]
