# Generated by Django 4.2.7 on 2026-05-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_companygoal_image_companygoal_media_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Website Visits',
                'ordering': ['-visited_at'],
            },
        ),
        migrations.AddField(
            model_name='contactenquiry',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Mark as read'),
        ),
        migrations.AddField(
            model_name='testdriveenquiry',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Mark as read'),
        ),
    ]
