# Generated by Django 4.2.7 on 2026-05-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_websitevisit_contactenquiry_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
